<section class="breadcrumb_area">
    <img class="breadcrumb_shap" src="<?= base_url(); ?>assets/front-end/img/breadcrumb/banner_bg.png" alt="">
    <div class="container">
        <div class="breadcrumb_content text-center">
            <h1 class="f_p f_700 f_size_50 l_height50 mb_20">Terms & Conditions</h1>
        </div>
    </div>
</section>
<section class="agency_service_area bg_color">
    <div class="container">
        <p>1.	By accessing or using the Website or by using the Service on the Website you agree to be bound by the Terms and Conditions set forth below including any additional guidelines and future modifications. Pack and Drop Logistics may add to, change or remove any part of these Terms and Conditions of Use at any time, without notice. Any changes to these Terms and Conditions of Use or any terms published on this Website apply as soon as they are released.</p>
        <p>2.	As a condition of your use of this Website, you agree that, you will provide your proper and accurate Name as per Passport or any other official ID issued by statutory body, Address, Email ID, Contact Number, mobile, direct landline, and will be solely responsible for the Information provided and in case of any error or mistake in provision of information, Pack and Drop Logistics will not be liable for the same.</p>
        <p>3.	You will use this Website to make only appropriate transactions for you or for another person for whom you are authorized to act, and will inform such other persons about the Terms of Use that apply to the transaction you have made on their behalf, including all rules and restrictions applicable. You indemnify Pack and Drop Logistics against any illegal purchases made by you or any other person either legally authorized or on account of your negligence.</p>
        <p>4.	Make sure that all information supplied by you on this Website is correct, accurate, current and complete.</p>
        <p>5.	If you have an online User Account with this Website, you will safeguard your login details such as login ID and password and will supervise the same. You will be entirely responsible for any use or misuse of your User Account by you and any other person.</p>
        <p>6.   logistics have the right in its sole discretion to deny access to anyone to this Website and the services we offer, at any time without notice and for any reason, including, but not limited to, for violation of these Terms of Use.</p>
        <p>7.	This Website and some other Website relating to Pack and Drop Logistics, its partners, subsidiaries, Service Providers, and so on are just for your own and non – business utilizes. It is entirely denied to You and of your partners and offshoots straightforwardly or by implication connected to You, to outline, scrap, hack, information mine, remove, gather, duplicate, disperse, trade, alter, offer or transmit any substance or material from this Site, including however not restricted to any information, indexed lists, content, pictures, sound, video or connections for any business, business or open reason.</p>
        <p>8.	The information and content provided on this Website including, the availability of logistics services, as well as the infrastructure used to provide such content and information, is proprietary to our Service Providers or us.</p>
        <p>9.	The Customer must have the learning of all laws not restricted to the reasonability of items being dispatched, bundling prerequisite, required documentation for Shipments, non-deserting, and so forth for the source and delivery destination. The Customer recognizes that the Service Provider and Pack and Drop Logistics acknowledge the Shipment on said to contain premise and just on the depiction given by the Customer on the waybill and other applicable Shipping Documents. The substance of the Shipment must be demonstrated by accurate portrayal in transit charge and other transportation archives on which the Shipment has been offered. Pack and Drop Logistics and the Service Provider accept no obligation to any individual for any misfortune or cost because of the Customer's inability to agree to this arrangement. The Customer additionally consents to hold Pack and Drop Logistics and the Service Provider safe from and against all cases, harms, liabilities, activities, misfortunes, expenses, and costs of any nature at all, emerging out of Customer's giving to Pack and Drop  Logistics or Service Provider inadequate, off base or false documentation or inability to provide the required data. By no means should Pack and Drop Logistics or the Service Provider be considered in charge of any risk emerging out of the products contained in the Customer's Shipment.</p>
        <p>10.	Assessment: Pack and Drop Logistics or the Service Provider or the Shipping Company or any administrative expert including traditions and security may open and examine your shipment whenever.</p>
        <p>11.	Protection: To obtain and keep up a protection to secure the Shipments amid the execution of the Services. The Customer's protection might have all hazard scope security against all dangers at each minute amid the travel and capacity of the Shipments. Client in this demonstration liberates Pack and Drop Logistics or the Service Provider or the Shipping Company from any, and all duty regarding any occurrence or incident happened amid the conveyance of the Shipment from its cause point to its last goal.</p>
        <p>12.	Documentation: To provide Pack and Drop Logistics and the Service Provider with a rundown of all the fundamental documentation required for the arrangement of the Services.</p>
        <p>13.	Relevant Duty Payment: To advise Pack and Drop Logistics and the Service Provider on the gathering paying the enforceable obligation, viz., either the Consignee or the Shipper. In the occasion, assuming either, the Shipper is the gathering paying the errand, or the Consignee declines to pay the assessment as informed at or post the booking regarding the Shipment, Pack and Drop Logistics should charge the Customer of such extra accuses along of a headway expense (i.e., a level of the obligation sum) and the Customer consents to pay Pack and Drop  Logistics, such duty inside five (7) working days from the date of raising such bills.</p>
        <p>14.	Odd Dimension or Heavy Weight Payment: To imply Pack and Drop Logistics on Shipments with either peculiar measurement or heavyweight for uncommon directions on bundling and extra charges apply. Such Shipments might be picked and conveyed just on due installment of such reserving.</p>
        <p>15.	All the Services available on the website are governed by the rules of service and regulations of the respective Service Provider. You are requested to refer to, acquaint and abide by those standards of service and practices of the particular Service Provider, before booking any shipping with us.</p>
    </div>
</section>